application: heroes-of-gilbert
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on
